### ISSUE TITLE
Cannot play lots of videos

### ISSUE THREAD

**Issue by simplyi** [0xced/XCDYouTubeKit#11]
Hi guys! 

I use youtube api to search for videos and play them using your approach. Half of videos do not play though some do but many, many do not. For example if I search for keyword "Madonna". But when I try to play those videos using apps like iTube, "Music Video" or "Play Tube" https://itunes.apple.com/ca/app/play-tube-free-player-for/id552248120?mt=8 .... they all play same videos no problem but XCDYouTubeVideoPlayer cannot play them. Can you help me figure how to make XCDYouTubeVideoPlayer play those youtube videos? For example this one: http://www.youtube.com/watch?v=GuJQSAiODqI   and there are many other I can give you URLs of.

**Comment by tungdangplus** [comment]
I can not find the answer to solve this problem so far. I'm stuck in this right now. I assumed that any video starting with Youtube Ads can not be play. And, when I try "youtube-ios-player-helper" in demo app, this problem is solved by adding playerVars: ["origin" : "https://www.youtube.com"]
I see that this topic is closed that means this problem is solved!!! Am I right? (hope).
I spent lots of time to find the answer... but I can't. Can someone lead me tho the right answer.
