### ISSUE TITLE
get the audio

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#127]
how i can get the audio link from the youtube video

**Comment by SoneeJohn** [comment]
Hello,

To do this simply follow these steps:

**Note**: I believe on OS X 10.9 and earlier the file needs to be converted/encoded for it in order to play properly. I am not sure that will work on iOS but, you can try. Finally, if you're downloading the file you need to add 'm4a' to the file extension plus, you may need to encode or convert it.
```
## Usage
```objc
// In the XCDYouTubeVideo.h in the section that define all the video quality
// Example:

typedef NS_ENUM(NSUInteger, XCDYouTubeVideoQuality) {
	   /**
        
        *  Video: 240p MPEG-4 Visual | 0.175 Mbit/s
        
        *  Audio: AAC | 36 kbit/s
        
        */
    
    XCDYouTubeVideoQualitySmall240  = 36,
    
    
    
    /**
     
     *  Video: 360p H.264 | 0.5 Mbit/s
     
     *  Audio: AAC | 96 kbit/s
     
     */
    
    XCDYouTubeVideoQualityMedium360 = 18,
    
    
    
    /**
     
     *  Video: 720p H.264 | 2-3 Mbit/s
     
     *  Audio: AAC | 192 kbit/s
     
     */
    
    XCDYouTubeVideoQualityHD720     = 22,
    
    
    
    /**
     
     *  Video: 1080p H.264 | 3–5.9 Mbit/s
     
     *  Audio: AAC | 192 kbit/s
     
     *
     
     *  @deprecated YouTube has removed 1080p mp4 videos.
     
     */
        
    XCDYouTubeVideoQualityAudio = 140,
    
    /**
     
     *  Audio: AAC | 128 kbit/s
   
 */
   
};

// Then simply fetch a video:

NSString *videoIdentifier = @"EdeVaT-zZt4"; // A 11 characters YouTube video identifier
[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:videoIdentifier completionHandler:^(XCDYouTubeVideo *video, NSError *error) {
    if (video)
    {
        // Do something with the `video` object, in this case the audio url

NSString *XCDYouTubeVideoQualityAudioString = [NSString    stringWithFormat:@"%@",video.streamURLs[@(XCDYouTubeVideoQualityAudio)]];

        }
    else
    {
        // Handle error
    }
}];

**Comment by syrakozz** [comment]
yes but i need only to download /stream only the audio , not the whole video and play the audio from it

**Comment by SoneeJohn** [comment]
This gives you a direct link to the audio stream.

**Comment by syrakozz** [comment]
seems great @0xced  can you merge it with the project , plz
 XCDYouTubeVideoQualityAudio = 140

**Comment by SoneeJohn** [comment]
**Note:** This may require additional manipulations.

**Comment by 0xced** [comment]
As @SoneeJohn pointed out, you can get the audio only stream by accessing the [itag 140](https://en.wikipedia.org/wiki/YouTube#Quality_and_formats) which is DASH M4A (AAC 128 kbit/s). I am not going to add a constant in `XCDYouTubeVideo.h` as I prefer to keep this list for audio/video streams formats supported by all iOS versions.

Anyway, you don't *need* a constant, accessing other streams by their itag is [documented](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.1/Classes/XCDYouTubeVideo.html#//api/name/streamURLs) and is as simple as `NSURL *audioOnlyStreamURL = video.streamURLs[@140];`

**Comment by FaridHaddad** [comment]
did you find a way to download the audio to your app ? the mp3 not m4a

**Comment by SoneeJohn** [comment]
@FaridHaddad You're going to have to convert the m4a into a MP3 file.

**Comment by FaridHaddad** [comment]
and if i want to save it locally to use the mp3 in offline mode do you know how ?

**Comment by FaridHaddad** [comment]
and do you know how to convert it to mp3 ? thanks

**Comment by SoneeJohn** [comment]
If you need to convert it unto an mp3 file then you can use this:
https://www.ffmpeg.org

**Comment by samirkhatri** [comment]
Please let me know how i can get .mp3 format url.

**Comment by samirkhatri** [comment]
Hi is there any way to get .mp3 format audio as output ? because i want to merge with image frame  and create new video.
Please help me on this.
