### ISSUE TITLE
The Request time out ; frequesntly comes

### ISSUE THREAD

**Issue by ananarola** [0xced/XCDYouTubeKit#134]
As i above mention while i play another video just 2nd video and the message comes that request time out. 

What to do.

**Comment by ananarola** [comment]
how to chnage the timeout interval. I got the request time out issue frequently

Need help !

**Comment by 0xced** [comment]
The timeout is intentionally [hardcoded to 10 seconds](https://github.com/0xced/XCDYouTubeKit/blob/646cba4400daca847799fee1eea4610e9dd68dc9/XCDYouTubeKit/XCDYouTubeVideoOperation.m#L108). Since it can take up to 6 network requests to get the playback URL of a video, I don’t intend to raise it.

I suggest you to check your network settings (DNS, VPN, Network Link Conditioner, etc.) because 10 seconds is usually enough, even under bad network conditions.

**Comment by ananarola** [comment]
hi there. thanks for reply.
Sometimes i get this error also : this video contains content from vevo. it is restricted from playback on certain sites.

for same video i get this error some time and sometime not
