### ISSUE TITLE
Get only video info?

### ISSUE THREAD

**Issue by guidev** [0xced/XCDYouTubeKit#149]
Hello,
I only need to get the stream urls, using getVideoWithIdentifier: is a bit too slow for this kind of operation, is there a way to only get videos' stream urls?

Thank you.

**Comment by 0xced** [comment]
No, there is no other way. The `getVideoWithIdentifier:completionHandler:` method is the only way to get the stream URLs. It can be slow for some videos since it involves performing up to 6 network requests and sometimes even executing some JavaScript.

Note that the next version of XCDYouTubeKit will perform all the parsing work on a background thread to improve the responsiveness of apps (see #147).
