### ISSUE TITLE
some video id not working

### ISSUE THREAD

**Issue by chaoswith** [0xced/XCDYouTubeKit#154]
video url : http://youtu.be/cXTNgLB7jjU

returns streaming url

https://r7---sn-ab02a0nfpgxapox-bh2e.googlevideo.com/videoplayback?key=yt5&mt=1435556624&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ip=1.223.40.18&expire=1435578332&sver=3&upn=EdEsS-iPGpM&lmt=1432380409973254&mv=m&source=youtube&ms=au&mime=video%2Fmp4&dur=131.192&pl=16&id=o-AF337QHMysPq4-dWQc4ZewhEjAIKN8V1CNg1rw_cpVLu&initcwndbps=4718750&itag=22&mn=sn-ab02a0nfpgxapox-bh2e&ipbits=0&mm=31&gcr=kr&ratebypass=yes&fexp=901816%2C9405183%2C9405960%2C9407141%2C9408142%2C9408420%2C9408710%2C9412843%2C9413503%2C9414965%2C9415332%2C9415450%2C9415635%2C9416103%2C9416126%2C9416456%2C9416484%2C9416675%2C9416729%2C9416916%2C948601%2C952640

but i can't see anything

**Comment by SoneeJohn** [comment]
I've had some users complain about video errors and black screens. However, they were mostly due to Vevo videos. Today, I pushed an update to both of my apps that utilizes this awesome class to use the new v2.2.0. I know the changelog doesn't mention anything in relation to fixing playback issues but, I will see if the reports stop after a couple days after most of my uses have adapted to the new version.

**Comment by 0xced** [comment]
*I can't see anything* isn't very helpful. Please see the [contributing guidelines](https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/CONTRIBUTING.md) to learn how to write a good bug report.

This video plays fine for me so I can't help without more information from you.

**Comment by 0xced** [comment]
No reply from OP for one month, so I’m closing the issue.
