### ISSUE TITLE
Change video identifier programmatically not working

### ISSUE THREAD

**Issue by huynhphan89** [0xced/XCDYouTubeKit#180]
I tried to changed video identifier programmatically but it doesnt work.
```
mPlayerController.videoIdentifier = content.mYouTubeId
mPlayerController.moviePlayer.prepareToPlay()
```
I saw setVideoIdentifer func is async. So I delayed 1s before call prepareToPlay func and then it works.
It'll be better if setVideoIdentifer func has a callback

Thanks

**Comment by 0xced** [comment]
Actually, there is a notification callback: [XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification](https://github.com/0xced/XCDYouTubeKit/blob/2.3.1/XCDYouTubeKit/XCDYouTubeVideoPlayerViewController.h#L28-L31). You can observe it in order to avoid the arbitrary 1s delay.

Unfortunately this notification is posted just before the content URL of the player is changed, so you need to do call `prepareToPlay` in the next run loop:
```objc
- (void) videoPlayerViewControllerDidReceiveVideo:(NSNotification *)notification
{
	dispatch_async(dispatch_get_main_queue(), ^{
		XCDYouTubeVideoPlayerViewController *videoPlayerViewController = notification.object;
		[videoPlayerViewController.moviePlayer prepareToPlay];
	});
}
```
