### ISSUE TITLE
Error "this video is not available in your country" but I'm able to watch it on youtube

### ISSUE THREAD

**Issue by logan-pratt** [0xced/XCDYouTubeKit#230]
I am trying to play the song Hello by Adele(Vevo) and get this error.
`[XCDYouTubeKit] Video operation finished with error: This video is not available in your country due to a copyright claim by NPG Music Publishing.
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video is not available in your country due to a copyright claim by NPG Music Publishing.";
    NSURL = "https://www.youtube.com/get_video_info?eurl=https://youtube.googleapis.com/v/EPV1QJvEuw4&hl=en&sts=16832&video_id=EPV1QJvEuw4";
}
Optional(Error Domain=XCDYouTubeVideoErrorDomain Code=150 "This video is not available in your country due to a copyright claim by NPG Music Publishing." UserInfo={NSURL=https://www.youtube.com/get_video_info?eurl=https://youtube.googleapis.com/v/EPV1QJvEuw4&hl=en&sts=16832&video_id=EPV1QJvEuw4, NSLocalizedDescription=This video is not available in your country due to a copyright claim by NPG Music Publishing.})
`
The weird thing is that I am in the US and it isn't blocked in the US.

**Comment by SepiaApps** [comment]
I have the same issue, all Vevo videos do not play. I believe this happened once before. YouTube has made some change and the author had to apply a fix.

**Comment by 0xced** [comment]
The error says **due to a copyright claim by NPG Music Publishing** so I believe it’s not available at all. Can you [watch it on YouTube](https://www.youtube.com/watch?v=EPV1QJvEuw4) in your web browser?

Also, the video with this error is *Purple Rain (Original Performed by Prince & The Revolution)*, not [Adele - Hello](https://www.youtube.com/watch?v=YQHsXMglC9A).

@SepiaApps I think you are talking about #231 which is already fixed in XCDYouTubeKit 2.5.1.

**Comment by SepiaApps** [comment]
@0xced Yes, that was my issue, disregard my previous post. Thanks!
