### ISSUE TITLE
Xamarin support?

### ISSUE THREAD

**Issue by avi22228** [0xced/XCDYouTubeKit#239]
Is there a Xamarin port for the library?

**Comment by 0xced** [comment]
I’m not familiar enough with Xamarin, but the process of creating a binding for a native iOS library is documented in the [Binding iOS Libraries](https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/) guide. Since XCDYouTubeKit can be built as a framework and as a pod, you should easily get it working.
