### ISSUE TITLE
Undefined symbols for architecture x86_64 only with Simulator 

### ISSUE THREAD

**Issue by nguyenvanbaoanh** [0xced/XCDYouTubeKit#251]
Hi All,

I am facing with this problem when I build my project with Simulator (there is not any issue with the Real Device)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCDYouTubeClient", referenced from:
      objc-class-ref in PlayingVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me!

<img width="1002" alt="screen shot 2016-05-22 at 12 26 07 pm" src="https://cloud.githubusercontent.com/assets/4743752/15452393/782d0d32-2018-11e6-863b-7818afb089be.png">

**Comment by 0xced** [comment]
I’m pretty confident this is not an issue with the XCDYouTubeKit library itself but this is an integration problem. Please ask this question on [Stack Overflow](http://stackoverflow.com/questions/ask) and don’t forget to provide some more details about your project setup so that people can help you.
