### ISSUE TITLE
Music pauses when switch apps / minimize

### ISSUE THREAD

**Issue by sajsanghvi** [0xced/XCDYouTubeKit#254]
Hey, right now when I switch apps or minimize the app the video pauses, and I have a workaround to play it as soon as it pauses. Does any one else experience this? Perhaps I am doing something wrong.

**Comment by mzgaljic** [comment]
This library uses AVPlayer. A Google search brings this up: https://developer.apple.com/library/ios/qa/qa1668/_index.html

See the "Special Considerations for Video Media" section.

**Comment by mzgaljic** [comment]
So basically, this is just how an AVPlayer works.

**Comment by sajsanghvi** [comment]
Dang, any solutions?

**Comment by Pranoy1c** [comment]
this is an avplayer problem and occurs for non youtube videos too. apple says in their docs that for background playback of videos in avplayer, you will need to remove the layer when the app is going to background. When app comes back to foreground, you will need to add the layer back in there. this way the audio can continue to play even when locked. NOTE that removing the layer / adding it back causes a tiny second skip. I don't think there is any way to solve that unfortunately. Most users are okay with that though.

**Comment by mzgaljic** [comment]
Yup, that's a great explanation. Sorry I didn't provide more details before, was on a mobile device.  :)

**Comment by 0xced** [comment]
Note that I implemented a [*BackgroundPlayback* category on MPMoviePlayerController](https://github.com/0xced/XCDYouTubeKit/blob/138a0be2f021152fd51a65bc2ac92a5b3524954b/XCDYouTubeKit%20Demo/iOS%20Demo/MPMoviePlayerController%2BBackgroundPlayback.m) in the iOS demo app that solves this exact problem. But as discussed in #103 and #131 this will never be part of the XCDYouTubeKit library.

**Comment by Pranoy1c** [comment]
@mzgaljic I am running my same app on iOS 10 developer beta and that problem of a tiny second skip seems to be solver. HURRAY!

**Comment by mzgaljic** [comment]
@Pranoy1c for real?!? That's awesome news - thanks for following up on the issue.

It's been a busy week, did not downloaded iOS 10 yet so I can't confirm.   :(

I wonder what they changed that 'fixed it'. Probably whatever code was handling the layer attach/detach?

**Comment by josharnoldjosh** [comment]
Hey guys, 

I know this is late, but I've found a solution that works without removing the layer, however, it still causes a small skip.

Basically, if you implement the following notification:

`NotificationCenter.default.addObserver(self, selector: #selector(MusicPlayerView.playerStateChanged), name: NSNotification.Name.MPMoviePlayerPlaybackStateDidChange, object: nil)
`

You can then have a method that will trigger the video to resume playing:

     func playerStateChanged() {
                   if playerController.moviePlayer.playbackState == .paused ||    playerController.moviePlayer.playbackState == .interrupted {
        
                          playerController.moviePlayer.play()

                 }
      }

Because if you follow the tutorials mentioned above for playback, the MPMoviePlayerController will pause whenever the app enters into a background mode. This code will cause the video to resume playing as soon as it is paused, with minimal delay. If anyone has a better solution I would gladly like to know!
