### ISSUE TITLE
Can't download offical stream video.

### ISSUE THREAD

**Issue by Noodlekim** [0xced/XCDYouTubeKit#263]
It was fine last night.

**Comment by ziopiero** [comment]
+1

**Comment by 0xced** [comment]
Please try with the latest version of XCDYouTubeKit, i.e. version 2.5.3. If you are still having problems, please open a new issue and make sure to have a look at the [contributing guidelines](https://github.com/0xced/XCDYouTubeKit/blob/020a4aacb7df323947b3a092b63e7b416705bdd7/CONTRIBUTING.md#submitting-issues) in order to write a good bug report so that I can help you.
