### ISSUE TITLE
error: This video is unavailable.

### ISSUE THREAD

**Issue by BharatAgarSoftTech** [0xced/XCDYouTubeKit#272]
https://www.youtube.com/shared?ci=eS9FbhOaci4

**Comment by BharatAgarSoftTech** [comment]
Please support for the issue.

**Comment by alankarmisra** [comment]
Maybe I'm wrong, but I think you're getting this error because you are using a _share url id_ and not the actual video id. 

See the bit in your url which shows : **shared?ci=eS9FbhOaci4**

If I manually go to the link and click on the name of the video, it takes me to the native youtube url which is:
https://www.youtube.com/watch?v=nClAiN9MXyc

So try using the video id _nClAiN9MXyc_ and it should work for this video.

**Comment by BharatAgarSoftTech** [comment]
yes, you are right man do you have an idea how to deal with this ?

**Comment by alankarmisra** [comment]
No sorry. I don't know how to translate share urls into canonical urls. Try asking around on StackOverflow. That's a better platform to discuss this imho considering it isn't an issue related to this specific library.

**Comment by SoneeJohn** [comment]
@BharatAgarSoftTech maybe try a regex expression.

**Comment by 0xced** [comment]
Thank you @alankarmisra for handling this issue perfectly.

@SoneeJohn: I don't see how a regular expression could help translating a share URL into a canonical URL.

**Comment by SoneeJohn** [comment]
@0xced apparently, I didn't fully comprehend the issue. I thought it was just an issue of getting the video identifier from the URL (`https://www.youtube.com/shared?ci=eS9FbhOaci4`). I thought everything after `ci` was the video identifier.

**Comment by BharatAgarSoftTech** [comment]
@SoneeJohn  The video identifier is different in both Urls.

Original video URL : https://www.youtube.com/watch?v=nClAiN9MXyc
 Shared video URL :  https://www.youtube.com/shared?ci=eS9FbhOaci4

**Comment by anmolagar** [comment]
Hi Team, Can we expect any support for share url in this library?
