### ISSUE TITLE
Is possible play audio without video?

### ISSUE THREAD

**Issue by JeromeTW** [0xced/XCDYouTubeKit#282]
Is possible play audio without video? Any advice is helpful.:)

**Comment by intari** [comment]
Why not?
I'm doing just that on app in AppStore. 
Your options are:
- using one of regular quality options with video and AVPlayer (traffic!.)
- get stream with itag 141 (AAC128) and AVPlayer (I have some...issues)
- get streams with  Opus/Vorbis  and something other instead of AVPlayer. You can also choose quality   (I use this).

**Comment by JeromeTW** [comment]
@intari Thanks your advice, I will try it later.

**Comment by d7laungani** [comment]
What do you mean get streams with Opus/ Vorbis. How do I get this . Thanks!

**Comment by SoneeJohn** [comment]
@d7laungani you need to get the itag value. 
![screen shot 2017-02-28 at 11 57 06 am](https://cloud.githubusercontent.com/assets/4827301/23412837/48efe292-fdad-11e6-9501-65e6d6e8792f.png)
(I got this table from Wikipedia: https://en.wikipedia.org/wiki/YouTube#ref_media_type_table_note_1)

the you simply use that as the key in the dictionary.

```
NSURL *streamURL = video.streamURLs[@<itag value here e.g 37>];
```
