### ISSUE TITLE
XCDYouTubeKit in UICollectionViewController

### ISSUE THREAD

**Issue by mobilityvalley** [0xced/XCDYouTubeKit#289]
Hi,

I'am trying to display a video inside the first item in a UICollectionViewController.
As it is not a TableView but a CollectionView, there is no "tableHeaderView" so I can not use the solution described here : https://github.com/0xced/XCDYouTubeKit/issues/35

I know it is not ideal but I have to display this video here and if the user scrolls and comes back the video has to continue.

I tried this design without success (in Swift 3) :

1/ I create a UIView : let videoView = UIView()
2/ I instantiate a XCDYouTubeController and I present it in the UIVIew (presentInView:videoView)
3/ Then in cellForItemAt: I assign the cell view to my view : videoView = cell.videoView

It does not show at all as I think it "is presenting" not added as a subview.

Any clues ?

```
import UIKit
import XCDYouTubeKit

class CollectionViewController: UICollectionViewController {
    
    var candies = ["Chocolate Bar", "Chocolate Chip", "Dark Chocolate", "Lollipop", "Candy Cane", "Jaw Breaker", "Caramel", "Sour Chew", "Gummi Bear", "Chocolate Bar", "Chocolate Chip", "Dark Chocolate", "Lollipop", "Candy Cane", "Jaw Breaker", "Caramel", "Sour Chew", "Gummi Bear"]
    var videoContainerView = UIView()

    
    override func viewDidLoad() {
        super.viewDidLoad()

        videoContainerView.backgroundColor = UIColor.cyan
        let videoPlayerViewController = XCDYouTubeVideoPlayerViewController(videoIdentifier: "eX3u0IlBBO4")
        videoPlayerViewController.present(in: videoContainerView)
        videoPlayerViewController.moviePlayer.play()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

    // MARK: UICollectionViewDataSource

    override func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 2
    }

    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if section == 0 {
            return 1
        } else {
            return candies.count
        }
    }

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let section = indexPath.section
        if section == 0 {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CellWithVideo", for: indexPath) as! CellWithVideo
            videoContainerView = cell.videoView
            return cell
        } else {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "OtherCell", for: indexPath) as! OtherCell
            return cell
        }
    }

}

class CellWithVideo: UICollectionViewCell {
    @IBOutlet weak var videoView: UIView!
}

class OtherCell: UICollectionViewCell {
    
}
```

**Comment by FlaviaBondJamesBondsHusband** [comment]
The problem is not with XCDYoutubeKit it's with your code. 

The problem is here `videoPlayerViewController.present(in: videoContainerView)`

The videoContainerView property is being set when this function is being called `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)`.

That function is only called when `reloadData:` is called on UICollectionView instance. This automatically happens when a viewController is loaded. 

However, you are setting the property in `viewDidLoad:` which is called way before `reloadData:` is called. 

The solution is to either call `reloadData:` before you set the variable in viewDidLoad, or, set the variable in `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)`.

I would probably recommend going with the former
