### ISSUE TITLE
How can Add youtube player like Whats app(PiP mode) using xcd ?

### ISSUE THREAD

**Issue by maulikshah09** [0xced/XCDYouTubeKit#480]
Hello 

 I have an shopping app and client want to pip mode like whats app. is possible pip mode in XCD player?

**Comment by SoneeJohn** [comment]
Hi,

You would have to use a custom solution on iPhone (since they don't support PiP with APIs from Apple), if you're using an iPad you can use `AVPlayerViewController` which supports PiP (see https://developer.apple.com/documentation/avkit/avplayerviewcontroller/1615821-allowspictureinpictureplayback)

**Comment by maulikshah09** [comment]
How can i don that

**Comment by SoneeJohn** [comment]
There is a 3rd party library that supports this here https://github.com/ky1vstar/PiPhone

**Comment by maulikshah09** [comment]
I have already tried that but not working

**Comment by SoneeJohn** [comment]
Okay, what have you tried? Maybe add your work as a GitHub repo so I can have a look.
