### ISSUE TITLE
SDK data issue

### ISSUE THREAD

**Issue by umairmian4u** [0xced/XCDYouTubeKit#98]
I am using XCDYouTubeKit and demo sample project working fine. I have created another test project it is also working fine but once I tried to add this in my original project it is giving strange errors like attached image and i am unable to track this issue.
![error](https://cloud.githubusercontent.com/assets/6328129/5578462/1b538414-9041-11e4-9707-e3366f821b00.png)

```objc
#import "XCDYouTubeKit/XCDYouTubeKit.h"

XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:@"9bZkp7q19f0"];
[videoPlayerViewController presentInView:self.view];
[videoPlayerViewController.moviePlayer play];
```

**Comment by umairmian4u** [comment]
in test code it is working fine but in actual code this is the issue

**Comment by 0xced** [comment]
Here is what I suggest. You start from your app and remove all the code which is not related to YouTube video playback. Maybe that means deleting 99% of your app, that's fine. Either you end up with working code and you can deduce which part of the code was causing the crash or you end up with a reproducible test app that you can share with me so that I can investigate the crash.

**Comment by 0xced** [comment]
No reply from OP for one month, so I’m closing the issue.
